server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: api-passenger
  redis:
    host: 101.34.39.86
    port: 6379
    database: 0
