server:
  port: 8085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.39.86:3306/service-map?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: w672118299

amap:
  key: 8e5a9b596293593cf4f089f0e7e1a07b
  sid: 848535