server:
  port: 8089
spring:
  application:
    name: service-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.34.39.86:3306/service-order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: w672118299